### PR TITLE
No need to protect branch at creation, there is a resource to handle that

### PR DESCRIPTION
**Pull request by mgsegner**
Hello,

I encountered issues with project creation and default branch protection. Let me detail my case.

**Issue**
When a repository is created the default branch is protected "implicilty" by the provider, but we can not manage the protection with resource gitlab_branch_protection because it ends with an error saying the branch is already protected.
So we are unable to define resource gitlab_branch_protection on the default branch to ensure it will stay protected over time.
I guess the current behavior aims to copy the GUI one, but it could be annoying with the terraform usage.

**Commit**
This commit will remove the "implicit" branch protection in the provider

**New behavior**
At creation time default branch will not be protected
Ensure the default branch is protected in terraform definition by using gitlab_branch_protection resource

This commit will change current behavior of project creation and an explicit definition of gitlab_branch_protection will be necessary after that.
Do you think this commit and the new behavior are right ?

Regards,

### CODE REVIEW

**Comment by mkjmdski** [comment]
This is great pull request! I had the issue with it that I couldn't change the default branch protection rules without importing it after creation what required manual step during repository provisioning. Although this behaviour will differ from default behaviour when user creates a repository from the UI so I'd suggest that you write explicitly in the documentation of the `gitlab_project` that default branch created by the resource will not be protected.

As work around before merging this pull request I suggest to anybody that encountred same issue as I did that you do not define default_branch in the repo and just set branch protection rule on not existing branch and then default branch will set automatically within the first commit to the repo.

**Comment by roidelapluie** [comment]
This is a breaking change that would need a major release of the provider.

**Comment by mgsegner** [comment]
Thanks for your feedback, I will have a look to documentation and update it as suggested

**Comment by mgsegner** [comment]
Documentation has been updated accordingly

**Comment by mkjmdski** [comment]
@mgsegner I suggest that you write this explicitly on line 45 regarding `default_branch` property. Otherwise people could miss it because most of us don't read entire documentation :D

**Comment by Stromweld** [comment]
I would check out #671 default branch protection resource doesn’t work on initial project creation. Work around is to disable branch protection on initial branch creation at group level. Then branch protection resource will work. out of the box defaults will throw an error that the branch is already protected even if you have different settings.

**Comment by mgsegner** [comment]
@Stromweld, you are right this commit will not cover every situations.
I thought of your proposal before this merge, but I thought too it was not really clean because a terraform create action would have to either create, update or do nothing and it is a weird behavior for me.
Unfortunately, it seems it is the most appropriate to cover every use cases

If everyone agrees, this PR can be closed and I will work on a new one to handle this situation in the gitlab_branch_protection if no one is already on it.

**Comment by roidelapluie** [comment]
The branch protection should not be done by the provider. As per terraform philosophy, we shoud stick to the original API behaviour, and not do a second call.

**Comment by armsnyder** [comment]
So the result of this change would be that a project initialized with a README would always be created with no protected branch, correct? That would be a different behavior than you would get using the GitLab API directly, where it would respect the branch protection settings configured for the instance or group.

I still wonder if maybe this PR is our best way of solving the issue of GitLab effectively creating a branch protection out-of-band.

This relates to #792 and more specifically #749.

**Comment by haarchri** [comment]
any progress here ? i wonder if we have a blocker to merge

**Comment by armsnyder** [comment]
This PR is currently blocked because we are lacking a consensus on how to approach the problem of the GitLab API creating resources out-of-band that may need to be also specified as Terraform resources.

I would like to see more discussion in #792 before we merge.

**Pull request closed without merging**
