### PR TITLE
Add gitlab_branch resource and data source

### PR DESCRIPTION
**Pull request by eddb7**
Hi I have been using this provider and required a way to automate and manage the creation and deletion of gitlab branches.
This allows the management of a `gitlab_branch` by adding it as a `resource` or `data` source block in terraform
The create, delete and read methods are using:  
 https://github.com/xanzy/go-gitlab/blob/master/branches.go#L188

The data structure for the resources is modelled on the response from 
https://docs.gitlab.com/ee/api/branches.html#get-single-repository-branch

The properties around  branch protection have been excluded for consistency, allowing this to work alongside the `gitlab_branch_protection` resources

It would be great to get some feedback and thoughts about wether this could potentially be integrated into the main package

### CODE REVIEW

**Comment by benguichard** [comment]
Hello, some update regarding the merge of this feature?
That will be a really nice plus have! :)

**Comment by eddb7** [comment]
> Hello, some update regarding the intregration of this feature?
> That will be a really nice plus have! 

I am actively trying to get this merged in but have had no response as of yet, it would be great to have a conversation with an admin around the feasibility and next steps of this release

**Comment by benguichard** [comment]
Hi @nicholasklick, if you have an occasion to take a looks on this merge request. Thank you 🙏

**Comment by creativeview** [comment]
@roidelapluie can this PR be reviewed?

**Comment by roidelapluie** [comment]
I started a review but I stumbled upon unrelated changes in the gitlab group.  I do not have the time to think about those changes now.

**Comment by eddb7** [comment]
> I started a review but I stumbled upon unrelated changes in the gitlab group. I do not have the time to think about those changes now.

Apologies, I had no review so I progressed my master branch with my current changes I am going to create a new PR here:
https://github.com/gitlabhq/terraform-provider-gitlab/pull/634

**Comment by eddb7** [comment]
New PR 
https://github.com/gitlabhq/terraform-provider-gitlab/pull/634

**Pull request closed without merging**
