### PR TITLE
Update Changelog for 3.8.0

### PR DESCRIPTION
**Pull request by nicholasklick**

### CODE REVIEW

**Comment by ThePlenkov** [comment]
Great work! Do you know when next release is planned and what's included?

We would be happy if those MRs are delivered with the following release:
https://github.com/gitlabhq/terraform-provider-gitlab/pull/634
https://github.com/gitlabhq/terraform-provider-gitlab/pull/588

**Comment by nagyv** [comment]
@nicholasklick As version 3.8.0 was published on November 19, can we close this PR?

**Comment by floh96** [comment]
@nicholasklick @nagyv this pr is still needed the changes from version 3.8.0 not in the Changelog yet

**Comment by nicholasklick** [comment]
@armsnyder this is fixed: https://github.com/gitlabhq/terraform-provider-gitlab/commit/52297e61ea213e4997bc159b3425622f3969075e

**Pull request closed without merging**
