### PR TITLE
Registry new docs location

### PR DESCRIPTION
**Pull request by attachmentgenie**
the [registry docs](https://www.terraform.io/docs/registry/providers/docs.html#migrating-legacy-providers-docs) suggest the docs location needs to change, this PR provides the proposed location change

related to #411

### CODE REVIEW

**Comment by nicholasklick** [comment]
@attachmentgenie Thanks for this.
It looks like this PR also includes https://github.com/gitlabhq/terraform-provider-gitlab/pull/413/commits/63593607151a8d94727714d1e31d0937583ba14a

Was that intentional as it seems like a duplication of https://github.com/gitlabhq/terraform-provider-gitlab/pull/412

**Review by armsnyder — APPROVED** [review]
Won't know till we try it 😄 

The workflow changes lgtm so I don't mind if you use this PR for that.

**Comment by attachmentgenie** [comment]
@nicholasklick sorry that's by mistake and not intentional

**Comment by nicholasklick** [comment]
@attachmentgenie I deleted those files from this PR so dont conflict with https://github.com/gitlabhq/terraform-provider-gitlab/pull/412

**Comment by attachmentgenie** [comment]
thanks!

**Pull request merged**
