### PR TITLE
Added missing scopes to deploy token

### PR DESCRIPTION
**Pull request by johannges**
This Pull Request is the same as Allow to create deploy token with all possible scopes. #695 
The only difference is, that i removed write_repository, because it is not allowed

### CODE REVIEW

**Comment by johannges** [comment]
Hey @armsnyder can you please approve this change?

**Comment by johannges** [comment]
Hey @armsnyder can you approve again,
i accidentally closed the pr while trying to update the branch to the newest master version.

I am hoping this will fix the problem in the ci

**Comment by johannges** [comment]
ok everything looks good for me, is there anything missing, before this can be merged?

**Comment by armsnyder** [comment]
Thanks @johannges, this looks good to me! I'll update the attribute documentation (https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/docs/resources/deploy_token.md#argument-reference) after merging.

**Review by armsnyder — APPROVED** [review]

**Pull request merged**
