### PR TITLE
Added Quotes in the example for group cluster

### PR DESCRIPTION
**Pull request by jose-bonilla**
Here is the same PR but from a forked Repo. Is this the correct workflow?

Added required quotes to the example for group_cluster.

### CODE REVIEW

**Comment by jose-bonilla** [comment]
Hi, is there anyone that could help me figure out why this failed the acceptance testing?

**Comment by armsnyder** [comment]
It's a flakey test. Possibly fixed by #363.

**Comment by armsnyder** [comment]
@jose-bonilla Can you rebase and see if it fixes the acceptance test?

**Comment by jose-bonilla** [comment]
@armsnyder Looks like we're good after the rebase. :)

**Comment by armsnyder** [comment]
Thanks!

**Pull request merged**
