### PR TITLE
Update the push rule if it exists already

### LINKED ISSUE #352: 422 {error: Project push rule exists}
### Terraform Version
Terraform v0.12.27
+ provider.gitlab v2.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project_push_rules

### Terraform Configuration Files
```hcl
resource "gitlab_project_push_rules" "project_push_rules" {
  project                       = gitlab_project.project.id
  commit_message_regex          = var.PROJECT_PUSH_RULES_COMMIT_MESSAGE_REGEX
  branch_name_regex             = var.PROJECT_PUSH_RULES_BRANCH_NAME_REGEX
  author_email_regex            = var.PROJECT_PUSH_RULES_AUTHOR_EMAIL_REGEX
  file_name_regex               = var.PROJECT_PUSH_RULES_FILE_NAME_REGEX
  deny_delete_tag               = var.PROJECT_PUSH_RULES_DENY_DELETE_TAG
  member_check                  = var.PROJECT_PUSH_RULES_MEMBER_CHECK
  prevent_secrets               = var.PROJECT_PUSH_RULES_PREVENT_SECRETS
  max_file_size                 = var.PROJECT_PUSH_RULES_MAX_FILE_SIZE
  # commit_committer_check        = var.PROJECT_PUSH_RULES_COMMIT_COMMITTER_CHECK
  # commit_message_negative_regex = var.PROJECT_PUSH_RULES_COMMIT_MESSAGE_NEGATIVE_REGEX
}

output project_push_rules {
  value = gitlab_project_push_rules.project_push_rules
}

variable "PROJECT_PUSH_RULES_COMMIT_MESSAGE_REGEX" {
  description = "(Optional, string) All commit messages must match this regex"
  type        = string
  default     = null
}

variable "PROJECT_PUSH_RULES_COMMIT_MESSAGE_NEGATIVE_REGEX" {
  type    = string
  default = null
}

variable "PROJECT_PUSH_RULES_BRANCH_NAME_REGEX" {
  description = "(Optional, string) All branch names must match this regex"
  type        = string
  default     = null
}

variable "PROJECT_PUSH_RULES_AUTHOR_EMAIL_REGEX" {
  description = "(Optional, string) All commit author emails must match this regex"
  type        = string
  default     = null
}

variable "PROJECT_PUSH_RULES_FILE_NAME_REGEX" {
  description = "(Optional, string) All commited filenames must not match this regex"
  type        = string
  default     = null
}

variable "PROJECT_PUSH_RULES_DENY_DELETE_TAG" {
  description = "(Optional, bool) Deny deleting a tag"
  type        = bool
  default     = false
}

variable "PROJECT_PUSH_RULES_MEMBER_CHECK" {
  description = "(Optional, bool) Restrict commits by author (email) to existing GitLab users"
  type        = bool
  default     = false
}

variable "PROJECT_PUSH_RULES_PREVENT_SECRETS" {
  description = "(Optional, bool) GitLab will reject any files that are likely to contain secrets"
  type        = bool
  default     = true
}

variable "PROJECT_PUSH_RULES_MAX_FILE_SIZE" {
  description = "(Optional, int) Maximum file size (MB)"
  type        = number
  default     = "0"
}

variable "PROJECT_PUSH_RULES_COMMIT_COMMITTER_CHECK" {
  description = "(Optional, bool) Users can only push commits to this repository that were committed with one of their own verified emails"
  type        = bool
  default     = false
}
```

### Debug Output
```hcl
  # gitlab_project_push_rules.project_push_rules will be created
  + resource "gitlab_project_push_rules" "project_push_rules" {
      + deny_delete_tag = false
      + id              = (known after apply)
      + max_file_size   = 0
      + member_check    = false
      + prevent_secrets = true
      + project         = "REDACTED"
    }

Error: POST https://gitlab.com/api/v4/projects/REDACTED/push_rule: 422 {error: Project push rule exists}

  on main.tf line 62, in resource "gitlab_project_push_rules" "project_push_rules":
  62: resource "gitlab_project_push_rules" "project_push_rules" {

```
### Expected Behavior
for a rule to be created

### Actual Behavior
error: Project push rule exists

### Steps to Reproduce
1. `terraform apply`

not related, but i'm seeing
```hcl
An argument named "commit_committer_check" is not expected here.
```
while that element exists in the documentation

### PR DESCRIPTION
**Pull request by ziporah**
This patch fixes #352 
if the Push rule creation throws 422 => error already exists on 
```
POST /api/v4/projects/21163411/push_rule HTTP/1.1  
...
---[ RESPONSE ]--------------------------------------
HTTP/2.0 422 Unprocessable Entity
...
{
 "error": "Project push rule exists"
}
...
```
We do a put update
```
PUT /api/v4/projects/21163411/push_rule HTTP/1.1 
...
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
...
```
Note: I believe the test would have to be adjusted to detect this issue, but I don't have a play environment available to validate this.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Hi,

I do not think this is correct as it would do things that are not in the plan. It would be against terraform principles.

**Comment by roidelapluie** [comment]
the correct fix would be to have the push rule as an optional computed field of the gitlab_repo.

**Comment by ziporah** [comment]
I totally agree, but then this shouldn't have been exposed for managing rules in terraform. Now this is just broken code. If you create a rule in terraform, it will not work, unless you import the existing ruleset, this forces you to do a sidestep out of the CI system. Importing doesn't even work unless you custom compile the latest provider with the import patch enabled. I don't know how this managed to get in in the first place, simply testing this on an empty created repository already breaks the terraform apply. 
I don't know if it is possible to get the information from gitlab and show the changes that would happen during creation of an unknown rule in terraform, without moving this code to a computed object on top of the repository object. I would reconsider allowing this patch and creating a refactoring request moving this total block to the repository object.

**Comment by roidelapluie** [comment]
@nicholasklick @armsnyder can we remove this resource in the 3.0 version of this module?

We can not accept this patch as it would overwrite user-created rules without warning in the plan.

**Comment by armsnyder** [comment]
@roidelapluie I agree, we should remove it and fold it into the `gitlab_project` resource.

While we're removing things, check out #219 which is in a similarly bad situation. I think we should also remove `gitlab_project_share_group`.

**Comment by nicholasklick** [comment]
@armsnyder @roidelapluie yes can we go ahead remove these resources to prep for a `3.0.0`?

**Comment by armsnyder** [comment]
@nicholasklick Great, I'll start on a PR. Here's the idea, slightly revised based on my reading of the discussion on #167 
- Remove `gitlab_project_push_rule` and move it into the `gitlab_project` resource
- Remove the `shared_with_groups` attribute from `gitlab_project` and make sure that the `gitlab_project_share_group` is working

Sorry if this delays 3.0.0 by a couple days, but it would resolve two more bugs and needs to be a breaking change.

**Comment by nicholasklick** [comment]
@armsnyder I dont mind the delay. We are currently still debugging the Registry release anyway.

**Comment by armsnyder** [comment]
Closing this since we merged #422.

**Pull request closed without merging**
