### PR TITLE
add build coverage regex

### PR DESCRIPTION
**Pull request by zawazawa0316**
Related issue: #596

### CODE REVIEW

**Comment by zawazawa0316** [comment]
I've finished fixing.

**Comment by armsnyder** [comment]
@zawazawa0316 Thanks for the contribution! I'd like to merge this since it is a small change. Can you resolve conflicts and fix the acceptance test failure?

```
=== RUN   TestAccGitlabProject_basic
    testing.go:705: Step 0 error: Check failed: Check 2/2 error: 1 error occurred:
        	* Check 30/41 error: attribute build_coverage_regex expected "foo" received ""
        
        
--- FAIL: TestAccGitlabProject_basic (5.95s)
=== RUN   TestAccGitlabProject_initializeWithReadme
--- PASS: TestAccGitlabProject_initializeWithReadme (6.81s)
=== RUN   TestAccGitlabProject_willError
    testing.go:705: Step 0 error: Check failed: Check 2/2 error: 1 error occurred:
        	* Check 13/41 error: attribute build_coverage_regex expected "foo" received ""
        
        
```

**Comment by zawazawa0316** [comment]
OK, I resolved conflicts and fixed.

**Review by armsnyder — APPROVED** [review]
Looks good!

**Pull request merged**
