### PR TITLE
Add support for `allow_force_push` parameter of protected branches (new in Gitlab 13.11.0)

### PR DESCRIPTION
**Pull request by pdecat**
This PR adds support for the [new `allow_force_push` parameter](https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches) for protected branches introduced in [Gitlab 13.11](https://about.gitlab.com/releases/2021/04/22/gitlab-13-11-released/#force-push-option-for-protected-branches) 
 
Depends on https://github.com/xanzy/go-gitlab/pull/1160

TODO:
* [ ] use next release of https://github.com/xanzy/go-gitlab when https://github.com/xanzy/go-gitlab/pull/1160 is merged and released

### CODE REVIEW

**Comment by pdecat** [comment]
This currently does not work as the API to update the `allow_force_push` parameter of protected branches [is not implemented](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/55261#note_591106026).

```
# make testacc TESTARGS="-v -run TestAccGitlabBranchProtection_basic -count=1"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 GITLAB_TOKEN=ACCTEST GITLAB_BASE_URL=http://127.0.0.1:8080/api/v4 go test -v ./gitlab -v -run TestAccGitlabBranchProtection_basic -count=1 -timeout 40m
=== RUN   TestAccGitlabBranchProtection_basic
    testing.go:705: Step 3 error: errors during apply:

        Error: PATCH http://127.0.0.1:8080/api/v4/projects/36/protected_branches/BranchProtect-8275739965283942723: 404 {error: 404 Not Found}

          on /tmp/tf-test452714993/main.tf line 11:
          (source code not available)


--- FAIL: TestAccGitlabBranchProtection_basic (7.65s)
FAIL
FAIL    github.com/gitlabhq/terraform-provider-gitlab/gitlab    7.725s
FAIL
make: *** [GNUmakefile:29: testacc] Error 1
```

In `TF_LOG=trace` mode, we see the `?allow_force_push=true` query string part:

```
---[ REQUEST ]---------------------------------------
PATCH /api/v4/projects/35/protected_branches/BranchProtect-4370415251300108582?allow_force_push=true HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: HashiCorp Terraform/0.12.7-sdk (+https://www.terraform.io) Terraform Plugin SDK/1.16.0 terraform-provider-gitlab
Content-Length: 0
Accept: application/json
Private-Token: ACCTEST
Accept-Encoding: gzip


-----------------------------------------------------
2021/06/02 18:36:56 [DEBUG] GitLab API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 404 Not Found
Content-Length: 25
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Date: Wed, 02 Jun 2021 16:36:56 GMT
Server: nginx
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Gitlab-Feature-Category: not_owned
X-Request-Id: 01F76SBJADP3F23T2XFJMPB9JW
X-Runtime: 0.007296

{
 "error": "404 Not Found"
}
-----------------------------------------------------
```

**Review by timofurrer — CHANGES_REQUESTED** [review]
Please rebase if you are still working on this, otherwise I'll close and may create a follow up issue.

**Comment by pdecat** [comment]
Hi @timofurrer, I'm still willing to implement this but to my knowledge, it is still not possible to update this parameter on a branch protection using the Gitlab API: https://docs.gitlab.com/ee/api/protected_branches.

A work-around would be to [delete the protection](https://docs.gitlab.com/ee/api/protected_branches.html#unprotect-repository-branches) then recreate it, but it does not feel really desired from my point of view as would drop the branch protection for a short amount of time if all goes well, and maybe longer in case of issues.

I can rebase, but am not sure what to do next.

**Comment by pdecat** [comment]
I've opened https://gitlab.com/gitlab-org/gitlab/-/issues/350955 to request the implementation for this in the Gitlab API.

**Comment by timofurrer** [comment]
@pdecat thanks for opening this. Let's see what's how to that turns out. I'm going to label this accordingly and keep it open ;)

**Comment by timofurrer** [comment]
Implemented with #877 . I'm still keeping an eye on https://gitlab.com/gitlab-org/gitlab/-/issues/350955 ;)

**Pull request closed without merging**
