### PR TITLE
Add support for commit_committer_check and reject_unsigned_commits in push rules

### LINKED ISSUE #202: [Bug] Unsupported argument: commit_committer_check
Hi there,

Getting error when `setting commit_committer_check` in `gitlab_project_push_rules`. According to [document](https://www.terraform.io/docs/providers/gitlab/r/project_push_rules.html#commit_committer_check), `commit_committer_check` should be supported.

### Terraform Version
+ Terraform v0.12.12
+ provider.gitlab v2.3.0

### Affected Resource(s)
- gitlab_project_push_rules

### Panic Output
```
Error: Unsupported argument

  on modules/gitlab_project/main.tf line 24, in resource "gitlab_project_push_rules" "push_rules":
  24:   commit_committer_check = true

An argument named "commit_committer_check" is not expected here.
```

### PR DESCRIPTION
**Pull request by jrdelarosa8**
Resolves #202, depends on #245

### CODE REVIEW

**Comment by roidelapluie** [comment]
There is not setter? is this computed? can you modify existing tests?

**Comment by jrdelarosa8** [comment]
Hey @roidelapluie, I can definitely look at the existing tests. Can you clarify what you mean by:

> There is not setter? is this computed?

Thanks!

**Comment by jrdelarosa8** [comment]
When creating a push rule resource via Terraform, we'll receive a 422 response because the push rule(s) already exist (new projects get push rules by default). 

This happens via [AddProjectPushRule](https://github.com/terraform-providers/terraform-provider-gitlab/blob/7dbdd83d27ebe937824de22f8b91ffbb71c897b9/gitlab/resource_gitlab_project_push_rules.go#L84) from the [client library](https://github.com/terraform-providers/terraform-provider-gitlab/blob/7dbdd83d27ebe937824de22f8b91ffbb71c897b9/vendor/github.com/xanzy/go-gitlab/projects.go#L1183).

It seems that we can get around this issue by not using the PUT/[ProjectPushRulesUpdate](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_push_rules.go#L63) function and removing the create since this will continue to cause problems/confusion.

Any thoughts?

**Comment by jrdelarosa8** [comment]
Are any maintainers available to take a look at my most recent question? @roidelapluie

**Comment by roidelapluie** [comment]
Mmmh that's a tricky one. I will think about it and come back to you.

**Comment by jrdelarosa8** [comment]
Do you have any additional thoughts?

**Comment by armsnyder** [comment]
Can you update the test please?

**Comment by armsnyder** [comment]
I like the idea of changing `AddProjectPushRule` to `EditProjectPushRule`, provided that it doesn't cause a problem where `EditProjectPushRule` also fails due to the push rule not existing, with the same exact race condition.

I also noticed in your change that you are reading these attributes, but you are not setting them in the create or update functions. That's probably what @roidelapluie meant.

**Comment by armsnyder** [comment]
Closing this since we merged #422 where we added these attributes but moved the config into `gitlab_project`. Thanks!

**Pull request closed without merging**
