### PR TITLE
add oauth token support

### PR DESCRIPTION
**Pull request by wuperry563**
Related to: https://github.com/gitlabhq/terraform-provider-gitlab/issues/60

### CODE REVIEW

**Comment by wuperry563** [comment]
@armsnyder Ready for review. This is my first contribution, so please feel free to let me know if somethings missing. 

Thanks!

**Comment by roidelapluie** [comment]
Thanks! I think it should be a dedicated option, we should not try to guess which kind of token we are dealing with.

**Comment by brandong1** [comment]
@nicholasklick Tagging you as requested.

**Comment by nicholasklick** [comment]
@wuperry563 please note that @roidelapluie is a maintainer for this project, so please kindly follow any guidance or feedback in order to move this towards merge. Thanks!

**Comment by wuperry563** [comment]
> Thanks! I think it should be a dedicated option, we should not try to guess which kind of token we are dealing with.

Sounds good. I'll look into this!

**Comment by armsnyder** [comment]
@roidelapluie I was thinking the same, but noticed something in the docs.

The [API docs](https://docs.gitlab.com/ee/api/#personalproject-access-tokens) say you can use a PAT the same as an OAuth token.

> You can also use personal or project access tokens with OAuth-compliant headers.

I propose changing the constructor from `gitlab.NewClient()` to `gitlab.NewOAuthClient()` for both PATs and OAuth tokens.

I tried it in a branch here and tests are passing: https://github.com/gitlabhq/terraform-provider-gitlab/compare/master...oauth-token

The only catch is that the the validation is slightly more strict, so I increased the length of our ACCTEST token. (Real PATs are the correct length, and I've verified that they work.)

**Comment by wuperry563** [comment]
@armsnyder It sounds like you already got it working and can submit a PR. Is there anything that I can help with as a first-time contributor? 

Should I close my PR?

**Comment by roidelapluie** [comment]
Oooh so it seems then that we are not "cheating" by using NewOAuthClient instead of NewClient. I guess we can transparently make the change in the code and slightly adapt our documentation.

**Comment by armsnyder** [comment]
Great! That being the case I've opened a new PR with my diff #686.

Thanks much to @wuperry563 for the initial work and getting us all looking into this!

**Pull request closed without merging**
