### PR TITLE
Change the default branch to main

### LINKED ISSUE #847: Let's change the default branch to `main`
It's overdue to change the default branch to `main`. 

@nagyv can you change that in the settings?

I can spot a reference to `master` here:

https://github.com/gitlabhq/terraform-provider-gitlab/blob/8cd2568e63320d127d215b1662a926d58186b8a2/.github/workflows/pr-check-conflicts.yml#L10

However, `main` is already included in that list, thus it shouldn't be an immediate problem. However, `master` can be removed :)

... and in the README when referencing the badges.

There is other `master` references in the test examples, which can also be changed independently.

### PR DESCRIPTION
**Pull request by nagyv**
## Description

Closes #847 

## PR Checklist

- [x] Resource attributes match 1:1 the names and structure of the API resource in [the GitLab API documentation](https://docs.gitlab.com/ee/api/).
- [x] [Examples](/examples) are updated with:
    - A \*.tf file for the resource/s with at least one usage example
    - A \*.sh file for the resource/s with an import example (if applicable)
- [x] New resources have at minimum a basic test with three steps:
    - Create the resource
    - Update the attributes
    - Import the resource
- [x] No new `//lintignore` comments that came from copied code. Linter rules are meant to be enforced on new code.

### CODE REVIEW

**Comment by nagyv** [comment]
@timofurrer @armsnyder Please, approve. I'll change the setting once the PR is approved.

**Comment by armsnyder** [comment]
Ah, I just commented in the issue, these workflows don't exist anymore, to we can either remove the badges or change the workflow id to "push"

**Comment by timofurrer** [comment]
Maybe also change the refrence in the labeler workflow :)

**Comment by armsnyder** [comment]
You could change the default branch to `master` _before_ making these changes, if you want.

**Comment by nagyv** [comment]
@timofurrer @armsnyder I changed the default branch and modified the badge.

**Review by armsnyder — APPROVED** [review]

**Comment by armsnyder** [comment]
@nagyv I got emails about some closed PRs when you switched the branch, but the links are giving 404 errors. Is that expected? (#481, #480, #478, #479). #567 also closed but still exists.

**Comment by nagyv** [comment]
I don't know



Adam Snyder ***@***.***> ezt írta (időpont: 2022. febr. 6.,
V, 21:49):

**Comment by floh96** [comment]
@nagyv did you rename the branch as described in the [GitHub docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch)?
Then open PRs should have been targeting the new branch and the URLs  should have been redirected.
In #567 I can see that you deleted the master branch and this closed the PR, this should not be the case if it was renamed following the steps from the docs.

**Comment by armsnyder** [comment]
Most PRs auto retargeted main. Just these few did not.

**Comment by nagyv** [comment]
Yes,  I renamed the branch.

Adam Snyder ***@***.***> ezt írta (időpont: 2022. febr. 6.,
Vas 22:51):

**Pull request merged**
