### PR TITLE
Update supported scopes on project_access_token

### LINKED ISSUE #1288: registry scopes not supported for project acces token resource
### Feature Description

The `gitlab_project_access_token` resource currently only allows the following scopes to be defined on the token:

- api
- read_api
- read_repository
- write_repository

But the [official gitlab api documentation](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html#scopes-for-a-project-access-token) lists 2 additional supported scope:

- read_registry
- write_registry

Let's update the validation rules to allow using them

### Do you want to implement this?

- [X] I would like to implement this myself 👷

### PR DESCRIPTION
**Pull request by elthariel**
## Description

Closes #1288

### PR Checklist Acknowledgement

- [x] I acknowledge that all of the following items are true, where applicable:
  - Resource attributes match 1:1 the names and structure of the API resource in [the GitLab API documentation](https://docs.gitlab.com/ee/api/).
  - [Examples](https://github.com/gitlabhq/terraform-provider-gitlab/tree/main/examples) are updated with:
    - A \*.tf file for the resource/s with at least one usage example
    - A \*.sh file for the resource/s with an import example (if applicable)
  - New resources have at minimum a basic test with three steps:
    - Create the resource
    - Update the attributes
    - Import the resource
  - No new `//lintignore` comments were copied from existing code. (Linter rules are meant to be enforced on new code.)

### CODE REVIEW

**Comment by elthariel** [comment]
Hum... It doesn't look like the test failures are related to my changes. `make testacc` passed without any issue on my machine

> Works on my machine (tm)

**Comment by elthariel** [comment]
Damn, this MR is a duplicate of #1264

**Review by timofurrer — APPROVED** [review]
LGTM 🎉

**Comment by Shocktrooper** [comment]
@elthariel after #1304 and #1301 are done mind pulling the latest changes and rerunning the tests to validate everything works.  Also might be worthwhile to add the 2 extra scopes to the `resource_gitlab_project_access_token_test.go` tests

**Comment by timofurrer** [comment]
@Shocktrooper yes, good catch!

**Comment by timofurrer** [comment]
@elthariel Could you please rebase onto the latest main (see #1304)?

**Comment by elthariel** [comment]
Hey,

I've realized I'm actually not going to use this feature after all, so this
is sadly kind of low priority at the moment :-/

I'll see what I can do

**Pull request closed without merging**
