### PR TITLE
Update license and use different encryption password

### PR DESCRIPTION
**Pull request by nicholasklick**
1. Updates with a renewed license
1. Using a new password to not conflict with the previous one.

### CODE REVIEW

**Comment by nicholasklick** [comment]
Fixes #392

**Comment by nicholasklick** [comment]
@armsnyder @roidelapluie can one of you take a look?

**Comment by armsnyder** [comment]
@nicholasklick Looks good, though I'm not sure what the `JulienPivotto.gitlab-license.enc` file is for.

**Comment by roidelapluie** [comment]
Yes and there is an empty Gitlab-license.encrypted

**Comment by nicholasklick** [comment]
@roidelapluie thats odd. Seems like the file shows +1.63 Kb https://github.com/gitlabhq/terraform-provider-gitlab/blob/72fd54b5f32c378aba9a112bc192abea799f32a3/Gitlab-license.encrypted

**Comment by nicholasklick** [comment]
@roidelapluie @armsnyder I removed `JulienPivotto.gitlab-license.enc` and the script that referenced it which I believe is cruft at this point?

**Comment by nicholasklick** [comment]
I assume we dont need `scripts/license.sh ` anymore?

**Pull request merged**
