### PR TITLE
Project mirroring

### PR DESCRIPTION
**Pull request by btyy77c**
Adds `mirror` and `mirror_trigger_builds` fields to Project

Related to Pull Request: https://github.com/gitlabhq/terraform-provider-gitlab/pull/449

Setup so EE tests can run against changes

### CODE REVIEW

**Comment by cnuss** [comment]
@nicholasklick @armsnyder here's the new PR that replaces #449 so that EE tests can run, and thanks to @btyy77c for their help.

Looks like we have green checkmarks across the board. Could you take a look and merge if you're happy, also let me know if there are more comments.

cc: @svenstaro @brijshah FYI since you have been tracking progress of this PR

**Comment by svenstaro** [comment]
Sooo how about we give this the good ol' merge? I really want this feature. :)

**Comment by btyy77c** [comment]
@armsnyder Are you available to review this PR?  I can try and find someone else if needed. 

Thanks!

**Comment by cnuss** [comment]
@armsnyder Pinging you again! Are you available to look at this PR?

**Comment by btyy77c** [comment]
@cnuss The GitLab team will try and review this tomorrow. 🎉

**Pull request merged**
