### PR TITLE
feat(project): add the pages_access_level parameter

### PR DESCRIPTION
**Pull request by jeremad**
This allows to control the visibility of the Pages, see
https://docs.gitlab.com/ee/user/project/pages/pages_access_control.html

Closes: #471

### CODE REVIEW

**Comment by jeremad** [comment]
Ready for review

**Comment by tangodev** [comment]
Hello @jeremad , is there a specific release cycle that this PR has to wait for? I'm asking because all the tests have passed OK, yet the change is not merged in. Just curious, no pressure.

**Comment by jeremad** [comment]
I am not a maintainer, I am waiting for a review :)

**Review by armsnyder — APPROVED** [review]
lgtm! Apologies for the delay on this.

**Pull request merged**
