### PR TITLE
Upgrade to SDK v2. Closes #552

### LINKED ISSUE #552: SDK v2
[Upgrade to the Terraform Plugin SDK v2](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html)

This is a potentially breaking change, since the minimum supported Terraform version becomes 1.12. HashiCorp recommends doing a major provider release when taking this upgrade.

### PR DESCRIPTION
**Pull request by timofurrer**
This is an actual working upgrade to the Terraform Plugin SDK v2 (not just updating the module reference as e.g. #461) does.

On the way a few lint errors could be removed, because I've switched to non-deprecated features (however, there are more to be updated - on that note: this PR is already quite large, therefore I suggest to get this merged before doing any more changes).

closes #552

### CODE REVIEW

**Comment by armsnyder** [comment]
Looks like you need to add the v2 version of `Set` to https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/errcheck_excludes.txt

**Comment by timofurrer** [comment]
Good catch - just added the `v2`. Can you trigger the checks again, please?

**Comment by timofurrer** [comment]
@roidelapluie I've just pushed a new commit fixing the reported linting issues.

One thing to note here is that I've only upgrade the *necessary*. I'll create follow up MRs for the other things once I've more time. However, I suggest to merge asap already :)

**Comment by armsnyder** [comment]
@roidelapluie @nicholasklick Is this ok to merge? The V2 SDK has been supported since Terraform 0.12, and [V1 is out of support](https://discuss.hashicorp.com/t/end-of-life-timeline-for-v1-of-the-terraform-plugin-sdk/24991?u=aareet), so we could probably get this into our next minor release without trouble.

**Comment by nagyv** [comment]
@timofurrer May I ask you to fix the conflict? I'll try to make sure we can merge this ASAP to avoid other conflicts.

@roidelapluie May I ask a review here? It would be great to merge it if you and @armsnyder agree.

**Comment by timofurrer** [comment]
@nagyv I've resolved the conflict.

**Comment by timofurrer** [comment]
@nagyv ci fails, due to the issue described here #785 - other issue might be shadowed and I'll get back to them once #785 is merged ...

**Comment by nagyv** [comment]
@timofurrer Thanks, I merged #785

**Comment by timofurrer** [comment]
@nagyv Alright, looks good so far. I want to emphasize again that this PR does the *necessary* things to upgrade to the SDK v2 - it doesn't use all the new "embraced" things, like using `diag` or `Context` aware CRUD functions, ...

Once this PR is merged, I'd like to continue working on further "modernize" the provider.

**Pull request merged**
