### PR TITLE
Add gitlab branch protection test

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
needs: doc

**Comment by nicholasklick** [comment]
@roidelapluie is this still relevant?

**Comment by armsnyder** [comment]
Still relevant, yes. The ImportState test steps are missing the required `ResourceName` field however, and docs should be updated.

#345 also adds this importer.

**Comment by timofurrer** [comment]
(almost) Duplicate of #345 and since this one is quite old, I'm going to close it. It either comes up again or will be solved with #345 .

**Pull request closed without merging**
