### PR TITLE
resource/gitlab_project: Fix passing `false` to API for explicitly set optional attributes

### PR DESCRIPTION
**Pull request by timofurrer**
I think at one point we have to decide on a consistent strategy about how and when to set optional attributes for the API options ... I have a few ideas and I'll write them up in an issue.

Closes: #1151

### CODE REVIEW

**Review by PatrickRice-KSC — COMMENTED** [review]
@timofurrer  - So I ran a quick test, and I verified that this did fix the issue (which logically it would), but it feels like we should have at least one test with some of the "false default" values running to make sure the fix works. Thoughts?

**Comment by timofurrer** [comment]
@PatrickRice-KSC absolutely. I've just added a test case, but didn't use `use_custom_template`, and the attributes required when importing from an URL to avoid a huge test setup. Since those are anyways `false` by default on upstream I think we are good here.

**Comment by timofurrer** [comment]
@PatrickRice-KSC note that I've also added the fixes for the group resource as described in #1154.

**Comment by PatrickRice-KSC** [comment]
> I've just added a test case, but didn't use `use_custom_template`, and the attributes required when importing from an URL to avoid a huge test setup. Since those are anyways `false` by default on upstream I think we are good here.

Makes complete sense, that'd be a ton of setup!

> note that I've also added the fixes for the group resource as described in https://github.com/gitlabhq/terraform-provider-gitlab/issues/1154.

Excellent, nice to knock out a couple issues with one PR!

**Review by PatrickRice-KSC — APPROVED** [review]

**Pull request merged**
