### PR TITLE
Remove vendor

### LINKED ISSUE #544: Check /vendor in CI
Check the integrity of /vendor in a GitHub action.

A frequent PR to this project is updating the xanzy/go-gitlab dependency. It would be good to add a GitHub action that checks that `go mod vendor` was run.

### PR DESCRIPTION
**Pull request by armsnyder**
Option, if we aren't vendoring anymore

Closes #544 
Closes #545

### CODE REVIEW

**Comment by roidelapluie** [comment]
Can you resolve the conflicts?

**Comment by armsnyder** [comment]
@roidelapluie I resolved the conflict by removing the "set up build variables" stage entirely, since the only remaining build variable was `GO111MODULE=on`, which shouldn't be required anymore since Go 1.13, as it will detect the `go.mod` in Go 1.13+.

**Comment by armsnyder** [comment]
@roidelapluie Can you take a look here? We have another go-gitlab dependency update incoming (#444), so it would good to merge this now if it's ready.

**Comment by roidelapluie** [comment]
Thanks!!

**Pull request merged**
