### PR TITLE
feat: bind branch protection permission for users

### PR DESCRIPTION
**Pull request by jeremad**
Implement https://docs.gitlab.com/ee/api/protected_branches.html#example-with-user--group-level-access for users only.

Closes: #441

### CODE REVIEW

**Comment by jeremad** [comment]
Ready for review, And EE acceptance test need to be run!

**Comment by armsnyder** [comment]
Thanks! There's an older but still open PR which also adds this feature (#329), where there's a disagreement on the design. I would have the same feedback for you, that it would be best to match the GitLab API field name and structure.

Here's a link to the discussion I'm referring to: https://github.com/gitlabhq/terraform-provider-gitlab/pull/329#discussion_r491660543

**Comment by jeremad** [comment]
OK thanks for the feedback.

**Comment by mattkasa** [comment]
@jeremad thank you so much for working on this 💯 

I'm going to go ahead and close this PR though, as it's been implemented in #556 👍

**Pull request closed without merging**
