### PR TITLE
Update vendor dependencies

### PR DESCRIPTION
**Pull request by horjulf**
- Updates all dependencies to latest minor/patch version.
- Fixes manual vendor change introduced at https://github.com/gitlabhq/terraform-provider-gitlab/pull/389

Needs:
- [x] https://github.com/xanzy/go-gitlab/pull/990

### CODE REVIEW

**Comment by horjulf** [comment]
Any concerns over bumping the `go.mod` required version to `1.15` ?

**Comment by horjulf** [comment]
The change introduced in #389 was also not upstream, created https://github.com/xanzy/go-gitlab/pull/990 to fix it.

**Comment by horjulf** [comment]
Upstream PR has been merged, updated `go-gitlab` to `v0.40.0`.

**Comment by zachkknowbe4** [comment]
@horjulf Is there any chance this could get merged to unblock #516?

**Comment by horjulf** [comment]
Fixed in https://github.com/gitlabhq/terraform-provider-gitlab/pull/523

**Pull request closed without merging**
