### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by willianpaixao**

### CODE REVIEW

**Comment by willianpaixao** [comment]
Hello @roidelapluie! Can I please get some review?

**Comment by willianpaixao** [comment]
Maybe @sirlatrom or @mattkasa?

**Review by mattkasa — APPROVED** [review]

**Comment by mattkasa** [comment]
@willianpaixao this looks great! really nice work cleaning up and adding linters in addition to adding examples for push rules, thanks for doing this! 💯

**Comment by sirlatrom** [comment]
> Maybe @sirlatrom or @mattkasa?

I am not a maintainer ☺️

**Pull request merged**
