### PR TITLE
fix: set project_key as required in gitlab_service_jira

### PR DESCRIPTION
**Pull request by solidnerd**
This will set the project key also required according to the current docs.

### CODE REVIEW

**Comment by ringods** [comment]
Hello @solidnerd, can you also fix the acceptance tests accordingly?

**Comment by sysadmiral** [comment]
Hello,

Something that threw me about this being "required" is that in the Gitlab UI for the Jira Integration there is no reference to the project key at all:

image

There is a mismatch between the fields in the UI and the ones used by the terraform provider that could lead to confusion at import time.

(API Url is another example field - present in UI but not mentioned in provider)

Is this a case of documentation needing updating or perhaps the underlying go-gitlab library needs updating to reflect newer gitlab versions?

I would be happy to help if you feel there are some actions that need to happen based on my comment.

Many Thanks

**Comment by timofurrer** [comment]
@armsnyder How do you suggest to move forward with this one here?

**Comment by armsnyder** [comment]
Let's close this PR for now. There is risk of it being a breaking change, plus it does not add functionality and there is no issue. We can re-open or move discussion to an issue if it is needed.

**Pull request closed without merging**
