### PR TITLE
Implement `ci_forward_deployment_enabled`

### PR DESCRIPTION
**Pull request by jeremad**
Related: #541

### CODE REVIEW

**Comment by pedromazala** [comment]
Hello there!

Is this PR moving forward? This would be really valuable 😅

**Comment by jeremad** [comment]
I'm like you, I am waiting :man_shrugging:

**Review by timofurrer — APPROVED** [review]

**Comment by timofurrer** [comment]
@nagyv LGTM.

@jeremad If you can, please rebase to latest master to ensure it still works :)

**Review by armsnyder — APPROVED** [review]
lgtm

**Review by timofurrer — CHANGES_REQUESTED** [review]
May I ask to rebase one more time.
We've made some significant changes to increase the maintainability of the project.

Which means that you should ask a `Description` field to the attribute schema definition.
With a `make reviewable` it will auto-generate the documentation 🎉

**Comment by jeremad** [comment]
Sure

**Comment by jeremad** [comment]
rebased

**Review by timofurrer — APPROVED** [review]

**Comment by timofurrer** [comment]
Thanks @jeremad for the improvement and your patience! It'll be available in the next release 🎉

**Pull request merged**
