### PR TITLE
Improve documentation and reference upstream API for every data source and resource

### PR DESCRIPTION
**Pull request by timofurrer**
This change improves the consistency of the data source and resource documentation and consistently references the upstream API documentation, which IMHO is usually essential to understand the full functionality of the underlying data source or resource.

### CODE REVIEW

**Review by armsnyder — APPROVED** [review]
Wow, thanks for the extensive change. I agree the upstream API should always be linked in some manner. The doc page is a good place to do it. Assuming it is simple to do, should we enforce this as a CI check so we don't regress on this? I could take a stab at writing an OPA policy and run it against the markdown files, unless anyone knows a better way.

**Comment by timofurrer** [comment]
@armsnyder OPA might be a little bit of an overkill, maybe some simple `grep` could already do the job :D 

However, up to you - I'm happy if there is *something* 🎉

**Comment by armsnyder** [comment]
@timofurrer Yeah I also want to avoid overkill. My thinking is, since this would be such a specific assertion, it should be added to the CI in an extensible way.

**Comment by armsnyder** [comment]
@timofurrer Done in https://github.com/gitlabhq/terraform-provider-gitlab/pull/942 using grep

**Pull request merged**
