### PR TITLE
Support `issues_template` and `merge_requests_template` in project resource

### LINKED ISSUE #517: Add support for managing `Default description template for merge requests` property
Hi there,

I want to submit feature request: 
Add support for managing `Default description template for merge requests` vie gitlab terraform provider. 

Currently I don't see any option to mange it using terraform. 

Option is under: Settings -> General -> Merge Request -> Default description template for merge requests

It could be done under `gitlab_project` resource or new resource could be added. 

Thanks.

### LINKED ISSUE #603: Support issues_template and merge_requests_template on gitlab_project
### Terraform Version
```
$ terraform -v
Terraform v0.14.10
```

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project

### Terraform Configuration Files
```hcl
resource "gitlab_project" "example" {
  name        = "example"
  description = "My awesome codebase"

  visibility_level = "public"

  issues_template         = "foo"
  merge_requests_template = "bar"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
The fields are available in gitlab_project both as a data source and as a resource.

### Actual Behavior
They are yet to be implemented 😄

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Only available in GitLab Premium and above.

### References
Dependencies:
- https://github.com/xanzy/go-gitlab/pull/1128

Docs:
- API: https://docs.gitlab.com/ee/api/projects.html#templates-for-issues-and-merge-requests
- Feature: https://docs.gitlab.com/ee/user/project/description_templates.html#set-a-default-template-for-merge-requests-and-issues

### PR DESCRIPTION
**Pull request by timofurrer**
This change supersedes #604 and 

Closes #603

Closes #517

### CODE REVIEW

**Comment by timofurrer** [comment]
@armsnyder can you trigger the EE acceptance tests for this one?

**Comment by armsnyder** [comment]
@timofurrer We don't have a way to trigger EE tests on PRs from forks. (Or we haven't found a way.)

You should have access to push branches to the repo now, so you could re-open this from a branch, which would run EE tests.

**Comment by timofurrer** [comment]
@armsnyder Unfortunately, I don't have permissions to push to the repo, yet.

**Comment by armsnyder** [comment]
@timofurrer Oh that's a bummer. I pushed the commit to a branch, so it should be running EE checks now.

**Comment by timofurrer** [comment]
@armsnyder actually, checking again, it seems like the tests are running with the `push` event, but not the `pull_request` event - strangely, the ce acc tests are running for both events ... did that happen because of the branch you pushed and it's referencing the same commit?! Or is that always the case ?

**Comment by armsnyder** [comment]
I'm also surprised to see the push checks showing up here and assumed also that it was because of the identical commit sha. Anyway it saves us from having to open a new PR since the checks are identical. 😄

**Comment by timofurrer** [comment]
@armsnyder do you have access to a EE instance to efficiently debug this?

**Comment by armsnyder** [comment]
It may take me some time to get it working. I have an EE license but am having some trouble getting it running on ARM, which is all I have available right now.

**Comment by armsnyder** [comment]
What I found while debugging this is that you cannot set the templates during creation. They need to be patched after the project is created.

See:

```shell
adam@adams-mbp ~ % curl -XPOST http://pc.local:8080/api/v4/projects --data 'name=test5&issues_template=foo&merge_requests_template=foo' -s -H 'PRIVATE-TOKEN: ACCTEST1234567890123' | jq '{id, issues_template, merge_requests_template}'
{
  "id": 43,
  "issues_template": null,
  "merge_requests_template": null
}
adam@adams-mbp ~ % curl -XPUT http://pc.local:8080/api/v4/projects/43 --data 'issues_template=foo&merge_requests_template=foo' -s -H 'PRIVATE-TOKEN: ACCTEST1234567890123' | jq '{id, issues_template, merge_requests_template}'
{
  "id": 43,
  "issues_template": "foo",
  "merge_requests_template": "foo"
}
```

I was also able to run the TestAccGitlabProject_IssueMergeRequestTemplates test with debug logs, but the above info should explain the problem.

https://gist.github.com/armsnyder/b9e0e61c52e401955f98a0e80f8f3aba

**Comment by timofurrer** [comment]
Ah, I see - Thanks! Was confused that `go-gitlab` supported that field for the create options, only now realised that it's been deprecated. I've pushed a fix.

**Review by armsnyder — APPROVED** [review]
lgtm!

**Comment by timofurrer** [comment]
@armsnyder can you force push to the branch in this repo again to re-trigger the EE acc tests, please 😇  ?

**Comment by armsnyder** [comment]
Ha, thanks for the reminder there! 🤪

**Comment by armsnyder** [comment]
I wish running EE tests were easier, either by making them always run with better protections, or adding chatops so we can trigger them with a `/run-ee` comment or something.

**Comment by armsnyder** [comment]
Ah this is not the first time I have had this thought 😛 #426

**Pull request merged**
