### PR TITLE
ADD: Update go-gitlab version to 0.36.0.

### PR DESCRIPTION
**Pull request by markopolo123**
Fixes https://github.com/gitlabhq/terraform-provider-gitlab/issues/348

Signed-off-by: Mark Sharpley <mcs94@cam.ac.uk>

### CODE REVIEW

**Comment by roidelapluie** [comment]
you should run go mod vendor

**Comment by Tensho** [comment]
Go-go-go!

**Comment by kunallanjewar** [comment]
@markopolo123 I'm going to push the vendor out later today so this can get merged.

**Comment by roidelapluie** [comment]
gentle reminder :)

**Comment by armsnyder** [comment]
Closing this since #404 updated us to latest

**Pull request closed without merging**
