### PR TITLE
Upgrade to go 1.19

### PR DESCRIPTION
**Pull request by timofurrer**
Anyone of the regular contributors against using go 1.19 already or have any doubts? 

@PatrickRice-KSC @Shocktrooper @armsnyder

### CODE REVIEW

**Comment by Shocktrooper** [comment]
No objections for me although in this PR is there a reason our go.sum file had so many deletions? I thought the make reviewable command cleaned that up or am I missing something?

**Comment by Shocktrooper** [comment]
Not sure if its 1.19 related but `TestAccGitlabProject_basic` is failing consistently in a GitPod on your branch when I try to run it specifically or all acceptance tests

**Comment by PatrickRice-KSC** [comment]
I wondered if GitPod would automatically update the `go` version to 1.19, and it looks like it does - that's quite nice!

**Comment by timofurrer** [comment]
@Shocktrooper was it a new environment? How exactly does it fail?

It passes for me in gitpod: 

image

@PatrickRice-KSC yeah, it's quite nice! Does it also fail for you though?

**Comment by Shocktrooper** [comment]
On a fresh GitPod running `make testacc` the failure is as follows
```
--- SKIP: TestAccGitlabProjectCluster_basic (0.09s)
=== CONT  TestAccGitlabUser_basic
=== CONT  TestAccGitlabProject_basic
    resource_gitlab_project_test.go:121: Skipping step 14/19 due to SkipFunc
    resource_gitlab_project_test.go:121: Step 15/19, expected an error with pattern, no match on: Error running apply: exit status 1
        
        Error: POST http://127.0.0.1:8080/api/v4/projects: 400 {message: {base: [The project is still being deleted. Please try again later.]}}
        
          with gitlab_project.foo,
          on terraform_plugin_test.tf line 2, in resource "gitlab_project" "foo":
           2: resource "gitlab_project" "foo" {
        
--- FAIL: TestAccGitlabProject_basic (86.92s)
=== CONT  TestAccGitlabServiceSlack_basic
--- PASS: TestAccGitlabReleaseLink_basic (13.07s)
```

Clicking on the button in VS code to run the `TestAccGitlabProject_basic` test results in a stacktrace error that I can assume is from a timeout
output that follows is truncated because of the large trace
```
Running tool: /home/gitpod/go/bin/go test -timeout 30s -run ^TestAccGitlabProject_basic$ github.com/gitlabhq/terraform-provider-gitlab/internal/provider -count=1 -v -tags=acceptance -parallel=2

=== RUN   TestAccGitlabProject_basic
=== PAUSE TestAccGitlabProject_basic
=== CONT  TestAccGitlabProject_basic
    /workspace/terraform-provider-gitlab/internal/provider/resource_gitlab_project_test.go:121: Skipping step 6/19 due to SkipFunc
    /workspace/terraform-provider-gitlab/internal/provider/resource_gitlab_project_test.go:121: Skipping step 7/19 due to SkipFunc
    /workspace/terraform-provider-gitlab/internal/provider/resource_gitlab_project_test.go:121: Skipping step 8/19 due to SkipFunc
    /workspace/terraform-provider-gitlab/internal/provider/resource_gitlab_project_test.go:121: Skipping step 10/19 due to SkipFunc
    /workspace/terraform-provider-gitlab/internal/provider/resource_gitlab_project_test.go:121: Skipping step 11/19 due to SkipFunc
    /workspace/terraform-provider-gitlab/internal/provider/resource_gitlab_project_test.go:121: Skipping step 12/19 due to SkipFunc
    /workspace/terraform-provider-gitlab/internal/provider/resource_gitlab_project_test.go:121: Skipping step 14/19 due to SkipFunc
panic: test timed out after 30s

goroutine 3082 [running]:
testing.(*M).startAlarm.func1()
        /home/gitpod/go/src/testing/testing.go:2036 +0x8e
created by time.goFunc
        /home/gitpod/go/src/time/sleep.go:176 +0x32
```

**Comment by timofurrer** [comment]
@Shocktrooper interesting - I assume it's a race condition and you just happen to hit it ...

I don't think it's per-se related to go 1.19 though and may be a potential race condition that "could" always happen.

**Comment by timofurrer** [comment]
@Shocktrooper It's weird though since we once accounted for this behavior here: https://github.com/gitlabhq/terraform-provider-gitlab/blob/main/internal/provider/resource_gitlab_project.go#L1591 ...

**Comment by Shocktrooper** [comment]
@timofurrer https://gist.github.com/Shocktrooper/44a533e5435d834d87ad49f822f0ae79

**Comment by timofurrer** [comment]
> @timofurrer https://gist.github.com/Shocktrooper/44a533e5435d834d87ad49f822f0ae79

I mean "debug output" as in running with `TF_LOG=debug`, sorry 💃 Would you mind re-running it?

**Comment by Shocktrooper** [comment]
@timofurrer https://gist.github.com/Shocktrooper/592d5630deaeaf6e1d495c46ec776ff1 here ya go :)

**Comment by timofurrer** [comment]
@Shocktrooper but this seems to be another issue now (this is also strange ...):

```
2022-08-19T16:10:32.206Z [WARN]  sdk.helper_resource: Error running Terraform CLI command: test_name=TestAccGitlabProject_basic test_step_number=9 test_terraform_path=/tmp/plugintest-terraform483074582/terraform test_working_directory=/tmp/plugintest3743424968/work1055766784
  error=
  | exit status 1
  | 
  | Error: Project push rules are not supported in your version of GitLab
  | 
  |   with gitlab_project.foo,
  |   on terraform_plugin_test.tf line 2, in resource "gitlab_project" "foo":
  |    2: resource "gitlab_project" "foo" {
  | 
  
```

**Comment by Shocktrooper** [comment]
@timofurrer That is super weird.  Where are you getting that error at?

**Comment by Shocktrooper** [comment]
@timofurrer I wonder if GitLab decided to do some push rule validation for non EE versions as the GitLab page has push rules as a premium and higher only [feature](https://docs.gitlab.com/15.2/ee/user/project/repository/push_rules.html)

**Comment by Shocktrooper** [comment]
Although the skip function should have caught that part of the test unless it didn't. This is weird

**Comment by timofurrer** [comment]
@Shocktrooper @PatrickRice-KSC I suggest that we go on with this change and address these failures in another issue. I doubt that they are related to the 1.19 upgrade - at least that's my best guess without any more information 🤞

**Review by armsnyder — APPROVED** [review]

**Comment by PatrickRice-KSC** [comment]
@timofurrer - Sorry, missed approving and merging these last week like we discussed on discord! I'll go ahead and merge them now since I see @armsnyder  approved them 🙂

**Pull request merged**
