### PR TITLE
Add protected_branch_ids to gitlab_project_approval_rule

### LINKED ISSUE #492: Add optional protected_branch_ids to the project_level_mr_approvals resource
### Enhancement proposal
Add  [protected_branch_ids](https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-project-level-rule) to the [project_level_mr_approvals](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project_level_mr_approvals) resource.

As it currenty stands my organization has different approval rules for different branches in place.  I would love to be able to scope the current resource to a branch instead of only being able to specify general rules for every branch on the project

### PR DESCRIPTION
**Pull request by sirlatrom**
Carry #540 due to fork from wrong repo (just for my own sake).

Fixes #492.

### CODE REVIEW

**Comment by armsnyder** [comment]
I see this is still a draft, but I don't think this will relate to #492, which is about adding a `protected_branch_ids` attribute to the [project_level_mr_approvals ](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project_level_mr_approvals) resource.

**Comment by sirlatrom** [comment]
> 
> 
> I see this is still a draft, but I don't think this will relate to #492, which is about adding a `protected_branch_ids` attribute to the [project_level_mr_approvals ](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project_level_mr_approvals) resource.

`gitlab_project_level_mr_approvals` does not configure protected branches, but `gitlab_project_approval_rule` does.

In order to properly provide the protected branch IDs, you would either have to configure them using a `gitlab_branch_protection` or, as will be added in this PR, look up the existing protected branches through a data source.

The current implementation of `gitlab_branch_protection` unconditionally overwrites any existing protection settings for the chosen branch, which is another issue of concern.

**Comment by sirlatrom** [comment]
@armsnyder This PR is now strictly about adding `protected_branch_ids` attribute to the [gitlab_project_approval_rule](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project_approval_rule) resource.

**Comment by Shocktrooper** [comment]
@nicholasklick I saw you were looking over pull requests in this project yesterday.  This merge request is also available to be reviewed/merged

**Review by mattkasa — APPROVED** [review]
@sirlatrom this looks great, thank you for adding this! 👍

**Comment by mattkasa** [comment]
@sirlatrom I'm seeing some acceptance test failures for this:

```
=== RUN   TestAccGitLabProjectApprovalRule_basic
    testing.go:705: Step 0 error: errors during plan:
        
        Error: "branch": required field is not set
        
          on /tmp/tf-test680098153/main.tf line 53:
          (source code not available)
        
        
--- FAIL: TestAccGitLabProjectApprovalRule_basic (0.19s)
=== RUN   TestAccGitLabProjectApprovalRule_import
    testing.go:705: Step 0 error: errors during plan:
        
        Error: "branch": required field is not set
        
          on /tmp/tf-test574411139/main.tf line 53:
          (source code not available)
        
        
--- FAIL: TestAccGitLabProjectApprovalRule_import (0.14s)
```

Any chance I could bug you for some help with these?

Seems like an issue with `branch             = gitlab_project.foo.default_branch`. I'm trying to figure out what the right fix is 🤔

**Comment by mattkasa** [comment]
Sorry for the noise, just talking out loud where I'm at looking at this...looks like `gitlab_project` doesn't expose a value for `default_branch` until after apply, and if I add `default_branch = "main"` to `gitlab_project.foo` and change `gitlab_branch_protection.default` `branch` to `branch = "main"`, then I run into:

```
=== RUN   TestAccGitLabProjectApprovalRule_basic
    testing.go:705: Step 0 error: errors during apply:
        
        Error: Incorrect attribute value type
        
          on /var/folders/nv/n1lf4tdx0fs9hkl3r88vt0_c0000gn/T/tf-test699686302/main.tf line 105:
          (source code not available)
            |----------------
            | gitlab_branch_protection.default.id is "41:main"
        
        Inappropriate value for attribute "protected_branch_ids": a number is
        required.
        
    testing.go:766: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: errors during refresh: Incorrect attribute value type: Inappropriate value for attribute "protected_branch_ids": a number is required.
        
        State: <nil>
--- FAIL: TestAccGitLabProjectApprovalRule_basic (2.33s)
```

Because `gitlab_branch_protection.default.id` is a two-part ID consisting of `project_id` and `branch`.

Not sure where to go next, I thought about adding a `branch_protection_id`, but as a Computed value, it doesn't seem like it's available for use at this point either 🤔

**Comment by armsnyder** [comment]
+1 to adding a computed `branch_protection_id` attribute to `gitlab_branch_protection`, and using it in the test.

And because it's related, there's an open PR for fixing the `default_branch` bug: #583

**Pull request merged**
