### PR TITLE
Move .goreleaser.yml to root

### PR DESCRIPTION
**Pull request by nicholasklick**
Moves `.goreleaser.yml` to project root

### CODE REVIEW

**Comment by armsnyder** [comment]
Ah, good catch, let's try another prerelease then?

**Comment by nicholasklick** [comment]
I cant find another example of a project where the `.goreleaser.yml` wasnt in the root dir. I think this config file is not being utilized in the `release` build

**Comment by armsnyder** [comment]
Yup, from the action: https://github.com/gitlabhq/terraform-provider-gitlab/runs/1131832157?check_suite_focus=true

```
✅ v3.0.0-pre tag found for commit '39a8664'
🏃 Running GoReleaser...
/opt/hostedtoolcache/goreleaser-action/0.143.0/x64/goreleaser release --rm-dist

   • releasing...     
```

**Comment by nicholasklick** [comment]
@armsnyder yeah lets merge this and try another prerelease since all the assets are not being generated

**Review by armsnyder — APPROVED** [review]

**Pull request merged**
