### PR TITLE
#464: Allow merge on skipped pipeline

### PR DESCRIPTION
**Pull request by mkjmdski**
Closes  https://github.com/gitlabhq/terraform-provider-gitlab/issues/464

As in the title, added simple read endpoint, please review.
API Ref: https://docs.gitlab.com/ee/api/projects.html

### CODE REVIEW

**Comment by mkjmdski** [comment]
@roidelapluie could you review please?

**Comment by roidelapluie** [comment]
It seems that the acceptance test isn't doing much. Can we have it changed, in testAccGitlabProjectUpdateConfig ?

**Comment by mkjmdski** [comment]
@roidelapluie I have added one check in the tests

**Comment by roidelapluie** [comment]
=== RUN   TestAccGitlabProject_willError
206
    testing.go:705: Step 0 error: Check failed: Check 2/2 error: 1 error occurred:
207
        	* Check 4/43 error: attribute allow_merge_on_skipped_pipeline expected "false" received "true"

**Comment by mkjmdski** [comment]
@roidelapluie could you reenable pipeline? It should be good now

**Comment by mkjmdski** [comment]
@roidelapluie do you have any idea why this test is keeping failing? Looks like resource doesn't set anything ??

**Comment by mkjmdski** [comment]
@roidelapluie I am not sure how to fix the issues with the test, could you give some little advice here?

**Comment by roidelapluie** [comment]
Can you set it to false in testAccGitlabProjectConfigDefaultBranch and true in the Update?  so we actually test that we can change it.

**Comment by roidelapluie** [comment]
Thank you, I will merge on green!

**Comment by mkjmdski** [comment]
finally fixed! :D

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
