### PR TITLE
support default_branch_protection on group

### PR DESCRIPTION
**Pull request by domcyrus**
Support using default_branch_protection on group. This is implementing one part of #667 

It will need a newer dependency of the "github.com/xanzy/go-gitlab" package. Currently only using github.com/xanzy/go-gitlab@v0.50.4-0.20210826102709-de0117b95832 (master) as the change of the needed default_branch_protection on group is only in master.

### CODE REVIEW

**Comment by domcyrus** [comment]
I've updated the PR to use go-gitlab 0.50.4.

**Comment by domcyrus** [comment]
Updated PR all tests run successfully.

**Comment by switchboardOp** [comment]
I'd love to see this merged now that the upstream dependency is released. Default branch protection is causing some issues for me. I was halfway through my own implementation when I found this PR. looks good @domcyrus!

**Comment by willianpaixao** [comment]
@domcyrus would you mind updating the documentation of the underlying resources as well?

**Comment by domcyrus** [comment]
@willianpaixao I added the missing documentation and also added unit tests.

**Comment by domcyrus** [comment]
Is there anything else needed?

**Comment by willianpaixao** [comment]
@domcyrus thanks! LGTM.

**Comment by switchboardOp** [comment]
fixes #667

**Comment by mkjmdski** [comment]
Hi @domcyrus. The newest go-gitlab is already in master you should take it's go mod files and this branch should be good to go.

**Comment by domcyrus** [comment]
@mkjmdski updated with upstream master.

**Comment by mkjmdski** [comment]
@roidelapluie could you please enable pipeline in here?

**Comment by roidelapluie** [comment]
Thanks!

**Comment by QuingKhaos** [comment]
As a note: it could have supported string values like `visibility_level` which are translated internally to the int access levels to be consistent..

**Comment by roidelapluie** [comment]
```
terraform-provider-gitlab $ ack PrivateVisibility
gitlab/util_test.go
46:                     Level:  gitlab.PrivateVisibility,

gitlab/util.go
80:             "private":  gitlab.PrivateVisibility,

vendor/github.com/xanzy/go-gitlab/types.go
488:    PrivateVisibility  VisibilityValue = "private"

```

**Comment by roidelapluie** [comment]
I think I now understand what you mean. In terraform, the best practice is to stick to the remote API as close as possible. If the gitlab API asks for an integer, I think we should not invent our own values.

**Comment by QuingKhaos** [comment]
> In terraform, the best practice is to stick to the remote API as close as possible.
I may agree.

> If the gitlab API asks for an integer, I think we should not invent our own values.

It's already done with the access control level values (`maintainer` instead of `40`) - sorry, confused them with the visibility level. Maybe not directly in the provider, but through the Go SDK. In this case I would prefer consistency with the other values and have

**Pull request merged**
