### PR TITLE
Allow disable/enable packages repository

### PR DESCRIPTION
**Pull request by jeremad**
With [GitLab 13.3](https://about.gitlab.com/releases/2020/08/22/gitlab-13-3-released/) the packages feature is generally available.
This PR creates an argument `packages_enabled` based on the [GitLab API](https://docs.gitlab.com/ee/api/projects.html#create-project) field of the same name to control the activation of this feature.

### CODE REVIEW

**Comment by jeremad** [comment]
There is a temp commit waiting for xanzy/go-gitlab#938 to be released.

**Comment by jeremad** [comment]
ready for review @armsnyder

**Review by armsnyder — APPROVED** [review]
lgtm! @roidelapluie Do you have a way that you usually verify `go.mod` changes? I saw you mention running `go mod vendor` in another PR.

**Comment by jeremad** [comment]
I did run go mod vendor! but you're right this should be automated somehow

**Pull request merged**
