### PR TITLE
Move to provider v2 ; remove vendor

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by armsnyder** [comment]
@roidelapluie Do you have an update on this? I have another PR with a lot of vendor changes which I'd like to rebase onto this if we're not vendoring anymore.

**Comment by nicholasklick** [comment]
@armsnyder is this PR now redundant?

**Comment by armsnyder** [comment]
@nicholasklick Only partially. The other part of this PR was to update the SDK to v2. However, I wonder if we need to plan for this, since HashiCorp suggests that [updating to v2 should be a major provider release](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html). (See #552 , [4.0 milestone](https://github.com/gitlabhq/terraform-provider-gitlab/milestone/2))

**Comment by roidelapluie** [comment]
Yes we want that

**Comment by timofurrer** [comment]
Already done with #725 .

**Pull request closed without merging**
